Incremental fixes used in demonstration notebooks (small update)
Small update to enable reviewers to reproduce the errors with demo
notebooks :

In the master branch, we organised the python scripts the following way :

   xESMF/xesmf/
         |_ xesmf.xesmf_v0_6_2_github
         |_ xesmf_fix1
         |_ xesmf_fix2
         |_ xesmf_fix10
         |_ __init__.py
         |_ frontend.py
         |_ ...

   - Full fixes are at the root directory xESMF/xesmf

   - The original xesmf version 0.6.2 is under xESMF/xesmf/xesmf_v0_6_2_github
     (except the tests directory)

   - Incremental fixes are under xESMF/xesmf/xesmf_fix2 (here for FIX2)

This a **temporary organisation** to enable testing quickly the fixes in the
jupyter-notebook (in descr. below) :

    Fix FIX2 can be loaded, e.g. here loading FIX2 :

    ```python
    import xesmf.xesmf_fix2 as xe
    ```

    Then you can change to the v6.0.2 version :

    ```python
    del xe
    import xesmf.xesmf_v0_6_2_github as xe

See in doc/notebooks (this repository) for full details :

    1.
Large_size_problems_Structured_grids_with_mask_FIX10_Issue9_with_xarray_DataArray_backed_by_sparse_COO.ipynb

    2.
Small_size_problems_Structured_grids_with_mask_Issues_1_and_2_with_xarray_DataArray_backed_by_sparse_COO.ipynb

The script part of the repo kept unchanged :

    1. Issue 9 and FIX10 :

       ```
       MemoryError: Unable to allocate 832. GiB for an array with shape
       (334167, 334000) and data type float64
       ```
       This problem is encountered with the package xesmf while
       encapsulating the sparse sparse.COO matrix of the regridding
weights
       under an xarray.DataArray structure.
       xarray fails interpreting the sparse.COO object hidden behind the
       numpy.ndarray type. It reserves Memory for the full size array
instead.
       This can cause MemoryError failures and/or result in the use of
an
       unecessary large amount of Memory.

    2. Issue 1 and 2 and FIX2 :

       ```
       AttributeError: 'numpy.ndarray' object has no attribute
       'to_scipy_sparse'
       ```

       Issue 1 arise when the regridding involves a source grid with
masked data.

       ```
       AttributeError: 'numpy.ndarray' object has no attribute 'coords'
       ```

       Issue 2 is related to the writing of the
       regridding weights to a netCDF file with the dedicated Class
       BaseRegridder method.

       Issue 1, 2 and 9 are all connected to the handling of the
       regridding weights as a sparse.COO array and/or an
xarray.DataArray
       backed by a sparse.COO array.

TODO : test fixes with das chunks