Incremental fixes used in demonstration notebooks
1. Issue 9 and FIX10 :

   ```
   MemoryError: Unable to allocate 832. GiB for an array with shape
   (334167, 334000) and data type float64
   ```
   This problem is encountered with the package xesmf while
   encapsulating the sparse sparse.COO matrix of the regridding weights
   under an xarray.DataArray structure.
   xarray fails interpreting the sparse.COO object hidden behind the
   numpy.ndarray type. It reserves Memory for the full size array instead.
   This can cause MemoryError failures and/or result in the use of an
   unecessary large amount of Memory.

2. Issue 1 and 2 and FIX2 :

   ```
   AttributeError: 'numpy.ndarray' object has no attribute
   'to_scipy_sparse'
   ```

   Issue 1 arise when the regridding involves a source grid with masked data.

   ```
   AttributeError: 'numpy.ndarray' object has no attribute 'coords'
   ```

   Issue 2 is related to the writing of the
   regridding weights to a netCDF file with the dedicated Class
   BaseRegridder method.

   Issue 1, 2 and 9 are all connected to the handling of the
   regridding weights as a sparse.COO array and/or an xarray.DataArray
   backed by a sparse.COO array.

See in doc/notebooks (this repository) for full details :

1. Large_size_problems_Structured_grids_with_mask_FIX10_Issue9_with_xarray_DataArray_backed_by_sparse_COO.ipynb

2. Small_size_problems_Structured_grids_with_mask_Issues_1_and_2_with_xarray_DataArray_backed_by_sparse_COO.ipynb